#!/usr/bin/env python3
"""
PWM Tone Generator

based on https://www.coderdojotc.org/micropython/sound/04-play-scale/
"""

import machine
import utime

# GP16 is the speaker pin
SPEAKER_PIN = 16

# create a Pulse Width Modulation Object on this pin
speaker = machine.PWM(machine.Pin(SPEAKER_PIN))

NOTES = {
    'C4': 262, 'G4': 392, 'A4': 440, 'B4': 494,
}

MELODY = [
    ('G4', 0.5), ('G4', 0.5), ('A4', 1), ('G4', 1), ('C5', 1), ('B4', 2),  # Happy birthday to you
]

def playtone(frequency: float, duration: float) -> None:
    speaker.duty_u16(1000)
    speaker.freq(frequency)
    utime.sleep(duration)


def quiet():
    speaker.duty_u16(0)

def play_song():
    for note, duration in MELODY:
        if note in NOTES:
            playtone(NOTES[note], duration)
        bequiet()
        sleep(0.05)  


print("Playing frequency (Hz):")

play_song()

# Turn off the PWM
quiet()
